services:
  haproxy:
    image: haproxy:3.1-alpine
    restart: unless-stopped
    networks:
      - twir
      - cloudflared
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

networks:
  twir:
    name: twir
    external: true
  cloudflared:
    external: true